# GitHub Actions workflow for Pull Requests
# https://help.github.com/actions

name: PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"

      # Install dependencies
      - run: yarn config set enableGlobalCache false
      - run: yarn install

      # Analyze code for potential problems
      - run: yarn prettier --check .
      - run: yarn lint
      - run: yarn tsc

      # Test
      - run: yarn test
        env:
          GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
